list-customers:
  handler: functions/api/list-customers/index.handler
  events:
    - http:
        path: /customers
        method: GET
        cors: ${file(./infra/api-gateway/cors.yml)}
        private: true
