nearby-customers:
  handler: functions/api/nearby-customers/index.handler
  events:
    - http:
        path: /customers/nearby
        method: GET
        cors: ${file(./infra/api-gateway/cors.yml)}
        private: true
